version: "2"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports: 
      - "3000:3000"
    command: "npm start"
  web:
    image: "nginx:latest"
    expose: 
      - "8000"
    ports: 
      - "8000:8000"